## Shape of an Array
The shape of an array is the number of elements in each dimension.

#### Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

## Reshaping arrays

Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension.

#### Reshape From 1-D to 2-D

Convert the following 1-D array with 12 elements into a 2-D array.
The outermost dimension will have 4 arrays, each with 3 elements:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#### Reshape From 1-D to 3-D
Convert the following 1-D array with 12 elements into a 3-D array.
The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

#### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

Convert 1D array with 8 elements to 3D array with 2x2 elements:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

#### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

### numpy.zeros() in Python
numpy.zeros() function creates a new array of specified shapes and types, filled with zeros. It is beneficial when you need a placeholder array to initialize variables or store intermediate results. We can create 1D array using numpy.zeros().

In [1]:
import numpy as np

#Create 1D array
arr = np.zeros(5)
print(arr)


# Creating a 2D array with 3 rows and 4 columns
arr = np.zeros((3, 4))

print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### numpy.ones() in Python
The numpy.ones() function returns a new array of given shape and type, with ones.

In [3]:
# Python Program illustrating
# numpy.ones method

import numpy as geek

b = geek.ones(2, dtype = int)
print(b)

a = geek.ones([2, 2], dtype = int)
print(a)

c = geek.ones([3, 3])
print(c)

[1 1]
[[1 1]
 [1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Creating Full Array
A full array is ideal when you need an array initialized with a specific value, such as zeros or ones, which is common in many mathematical computations.

In [ ]:
import numpy as np
fullArr = np.full((3, 4), 5)
print(fullArr)

#### numpy.arange() in Python
numpy.arange() function creates an array of evenly spaced values within a given interval. It is similar to Python's built-in range() function but returns a NumPy array instead of a list.

In [ ]:
import numpy as np 
a = np.arange(5 , 10)
print(a)

#### numpy.eye() in Python
numpy.eye() is a function in the NumPy library that creates a 2D array with ones on the diagonal and zeros elsewhere. 

In [4]:
import numpy as np

# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
