### What is Numpy?
NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python and it is an open source project. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing numpy:

#### 1D Array

In [ ]:
# import numpy library

import numpy as np 

In [2]:
# Create a numpy array
import numpy as np 
a = np.array([0, 1, 2, 3, 4])
print(a)

[0 1 2 3 4]


In [4]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


#### 2D Array

In [2]:
import numpy as np 
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

#### Multi Dimentional Array

### Checking NumPy Version
The version string is stored under version attribute.

In [5]:
print(np.__version__)

2.3.5


### Type
If we check the type of the array we get numpy.ndarray:

In [6]:
# Check the type of the array

type(a)

numpy.ndarray

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the data type of the array’s elements. In this case, it's a 64-bit integer:

In [7]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

The astype() method converts an array to a specified data type.

In [1]:
import numpy as np

# create a 1D array
array = np.array([0, 1, 2, 3, 4, 5])

# convert to different data types
floatArray = array.astype(float)
complexArray = array.astype(complex)
boolArray = array.astype(bool)
stringArray = array.astype(str)

print("Original Array:", array)
print("Float Array:", floatArray)
print("Complex Array:", complexArray)
print("Boolean Array:", boolArray)
print("String Array:", stringArray)

Original Array: [0 1 2 3 4 5]
Float Array: [0. 1. 2. 3. 4. 5.]
Complex Array: [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
Boolean Array: [False  True  True  True  True  True]
String Array: ['0' '1' '2' '3' '4' '5']


### Assign value
We can change the value of the array. Consider the array c:

In [8]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

We can change the first element of the array to 100 as follows:

In [9]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

We can change the 5th element of the array to 0 as follows:

In [10]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

### Indexing
Indexing in NumPy means accessing specific elements from an array using their position (index). It is very similar to Python lists but more powerful.

#### Indexing in 1D Array

In [9]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element → 10
print(arr[2])   # Third element → 30
print(arr[-1])  # Last element → 50

10
30
50


#### Indexing in 2D Array


In [10]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr[0, 0])  # Row 0, Column 0 → 1
print(arr[1, 2])  # Row 1, Column 2 → 6

1
6


#### Indexing in 3D Array

In [11]:
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]]
])

print(arr[0, 1, 2])  # → 6

6


#### Fancy Indexing
Fancy indexing means selecting elements from a NumPy array using a list or array of indices instead of a single index or slice.

In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

result = arr[[0, 2, 4]]

print(result)   # [10 30 50]

[10 30 50]


### Slicing
Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].The element at end index is not being included in the output.

We can select the elements from 1 to 3 and assign it to a new numpy array d as follows:

In [11]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

We can assign the corresponding indexes to new values as follows:

In [12]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

We can also define the steps in slicing, like this: [start:end:step].

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


If we don't pass start its considered 0

In [14]:
print(arr[:4])

[1 2 3 4]


If we don't pass end it considers till the length of array.

In [15]:
print(arr[4:])

[5 6 7]


If we don't pass step its considered 1

In [16]:
print(arr[1:5:])

[2 3 4 5]


### Assign Value with List
Similarly, we can use a list to select more than one specific index. The list select contains several values:

In [17]:
# Create the index list

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

We can use the list as an argument in the brackets. The output is the elements corresponding to the particular indexes:

In [18]:
# Use List to select elements

d = c[select]
d

array([100,   2, 300, 400])

We can assign the specified elements to a new value. For example, we can assign the values to 100 000 as follows:

In [19]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

### Other Attributes
Let's review some basic array attributes using the array a:

In [20]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

The attribute size is the number of elements in the array:

In [21]:
# Get the size of numpy array

a.size

5

The next two attributes will make more sense when we get to higher dimensions but let's review them. The attribute ndim represents the number of array dimensions, or the rank of the array. In this case, one:

In [22]:
# Get the number of dimensions of numpy array

a.ndim

1

The attribute shape is a tuple of integers indicating the size of the array in each dimension:

In [23]:
# Get the shape/size of numpy array

a.shape

(5,)

In [3]:
# zeros method
import numpy as np
zeros_array = np.zeros(3)
zeros_array

array([0., 0., 0.])

In [4]:
# ones method
import numpy as np
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [5]:
# ones 2D Array
import numpy as np
ones = np.ones([3, 4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# range in numpy
import numpy as np
range = np.arange(1, 10, 2)
range

array([1, 3, 5, 7, 9])

In [6]:
# full method 
import numpy as np
full = np.full([3, 4], 7)
full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
# Identity matrix 1 in digonal and 0 remaining part
iden = np.eye(4)
iden

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Boolean Masking (Filtering)
Boolean masking is a method used to filter elements from a NumPy array based on a condition (True/False).

In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

result = arr[arr > 25]

print(result)   # [30 40 50]

[30 40 50]


### Numpy Statistical Functions

In [26]:
# Get the mean of numpy array

mean = a.mean()
mean

np.float64(0.0)

In [27]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

np.float64(1.0)

In [28]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [29]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

np.int64(5)

In [30]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

np.int64(-1)

### Numpy Array Operations
You could use arithmetic operators directly between NumPy arrays

#### Array Addition
Consider the numpy array u:

In [31]:
u = np.array([1, 0])
u

array([1, 0])

Consider the numpy array v:

In [32]:
v = np.array([0, 1])
v

array([0, 1])

We can add the two arrays and assign it to z:

In [33]:
# Numpy Array Addition

z = np.add(u, v)
z

array([1, 1])

The operation is equivalent to vector addition:

#### Array Subtraction
Consider the numpy array a:

In [45]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

Consider the numpy array b:

In [47]:
b = np.array([5, 10, 15])
b

array([ 5, 10, 15])

We can subtract the two arrays and assign it to c:

In [48]:
c = np.subtract(a, b)

print(c)

[ 5 10 15]


### Array Multiplication
Consider the vector numpy array y:

In [49]:
# Create a numpy array

x = np.array([1, 2])
x

array([1, 2])

In [50]:
# Create a numpy array

y = np.array([2, 1])
y

array([2, 1])

We can multiply every element in the array by 2:

In [51]:
# Numpy Array Multiplication

z = np.multiply(x, y)
z

array([2, 2])

#### Array Division
Consider the vector numpy array a:

In [52]:
a = np.array([10, 20, 30])
a

array([10, 20, 30])

Consider the vector numpy array b:

In [53]:
b = np.array([2, 10, 5])
b

array([ 2, 10,  5])

We can divide the two arrays and assign it to c:

In [54]:
c = np.divide(a, b)
c

array([5., 2., 6.])

### Dot Product
The dot product of the two numpy arrays u and v is given by:

In [55]:
X = np.array([1, 2])
Y = np.array([3, 2])

In [56]:
# Calculate the dot product

np.dot(X, Y)

np.int64(7)

### Adding Constant to a Numpy Array

In [63]:
# Create a constant to numpy array

u = np.array([1, 2, 3, -1]) 
u

array([ 1,  2,  3, -1])

Adding the constant 1 to each element in the array:

In [64]:
# Add the constant to array

u + 1

array([2, 3, 4, 0])

#### Aggregation function 
Aggregation functions in NumPy are used to perform operations on multiple values and return a single summarized result. These are very useful in data analysis when you want to calculate totals, averages, minimums, etc.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7,])

print("Sum:", np.sum(arr))         # 15
print("Mean:", np.mean(arr))       # 3.0
print("Min:", np.min(arr))         # 1
print("Max:", np.max(arr))         # 5
print("Std:", np.std(arr))         # Standard deviation
print("variance", np.var(arr)) # Variance tells us how spread out the values are from the average (mean).
print("Product", np.prod(arr)) # It multiplies all values in the array and returns a single result.
print("cumulative_sum", np.cumsum(arr)) #It keeps adding elements one by one and stores the result at each step.
print("cumulative_product", np.cumprod(arr)) # Instead of multiplying all numbers at once, it multiplies step by step and stores each result.

Sum: 28
Mean: 4.0
Min: 1
Max: 7
Std: 2.0
variance 4.0
Product 5040
cumulative_sum [ 1  3  6 10 15 21 28]
cumulative_product [   1    2    6   24  120  720 5040]


### Reshaping in NumPy
Reshaping means changing the shape (dimensions) of an array without changing its data.

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


In [15]:
# 1D → 2D
arr = np.array([1, 2, 3, 4])
print(arr.reshape(2, 2))

[[1 2]
 [3 4]]


In [16]:
# 2D → 1D (Flatten)

arr = np.array([[1, 2], [3, 4]])
print(arr.reshape(-1))   # [1 2 3 4]

[1 2 3 4]


In [17]:
# Reshaping into 3D
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(1, 2, 3))

[[[1 2 3]
  [4 5 6]]]


In [20]:
# .ravel() Changes in r may affect original array
import numpy as np
arr = np.array([[1, 2], [3, 4]])
r = arr.ravel()
print(r)   # [1 2 3 4]

[1 2 3 4]


In [21]:
# .flatten() Changes in f do NOT affect original array
arr = np.array([[1, 2], [3, 4]])
f = arr.flatten()
print(f)   # [1 2 3 4]

[1 2 3 4]


### Mathematical Functions
We can access the value of pi in numpy as follows :

In [65]:
# The value of pi

np.pi

3.141592653589793

In [67]:
# Create the numpy array in radians

x = np.array([0, np.pi/2 , np.pi])
x

array([0.        , 1.57079633, 3.14159265])

We can apply the function sin to the array x and assign the values to the array y; this applies the sine function to each element in the array:

In [68]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

## Advance Numpy

### Insert
It allows you to insert values at specific positions in 1D, 2D, or higher-dimensional arrays.

In [23]:
# Insert in 1D Array

import numpy as np
arr = np.array([1, 2, 3, 4])
new_arr = np.insert(arr, 2, 99)
print(new_arr)   # [1 2 99 3 4]

[ 1  2 99  3  4]


In [24]:
# Insert Multiple Values

arr = np.array([1, 2, 3])
new_arr = np.insert(arr, 1, [10, 20])
print(new_arr)   # [1 10 20 2 3]

[ 1 10 20  2  3]


In [27]:
# Insert in 2D Array (Row-wise)
arr = np.array([[1, 2],
                [3, 4]])
new_arr = np.insert(arr, 1, [9, 9], axis=0)
print(new_arr)

[[1 2]
 [9 9]
 [3 4]]


### Append
append is used to add elements at the end of an array.

In [28]:
# Append in 1D Array

import numpy as np
arr = np.array([1, 2, 3])
new_arr = np.append(arr, 4)
print(new_arr)   # [1 2 3 4]


[1 2 3 4]


In [29]:
# Append Multiple Values

arr = np.array([1, 2, 3])
new_arr = np.append(arr, [4, 5, 6])
print(new_arr)   # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [30]:
# Append in 2D Array (Row-wise)

arr = np.array([[1, 2],
                [3, 4]])
new_arr = np.append(arr, [[5, 6]], axis=0)
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


### Concatenate
Concatenate means joining two or more arrays together.

In [31]:
# Concatenate in 1D Array

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))
print(result)   # [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [32]:
# Concatenate in 2D Array (Row-wise)

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6]])
result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


### Remove
NumPy does not have a direct remove() function like Python lists.
nstead, we use:

✅ np.delete()

In [33]:
# Remove from 1D Array

import numpy as np
arr = np.array([10, 20, 30, 40])
new_arr = np.delete(arr, 2)
print(new_arr)   # [10 20 40]

[10 20 40]


In [34]:
# Remove Multiple Elements

arr = np.array([10, 20, 30, 40, 50])
new_arr = np.delete(arr, [1, 3])
print(new_arr)   # [10 30 50]

[10 30 50]


In [35]:
# Remove Row (2D Array)

arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
new_arr = np.delete(arr, 1, axis=0)
print(new_arr)


[[1 2]
 [5 6]]


### Stacking
Stacking means combining multiple arrays along a new axis (dimension).
- np.stack()	General stacking (new axis)
- np.vstack()	Vertical stacking (row-wise)
- np.hstack()	Horizontal stacking (column-wise)

In [36]:
# np.stack()

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.stack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]]


In [37]:
# np.vstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]]


In [38]:
# np.hstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))

print(result)

[1 2 3 4 5 6]


### Splitting
Splitting means dividing one array into multiple smaller arrays.

#### np.split()

In [39]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)

print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


#### np.array_split() (Unequal Allowed)


In [40]:
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)

print(result)

[array([1, 2]), array([3, 4]), array([5])]


#### np.hsplit() (Horizontal Split)

In [41]:
arr = np.array([[1, 2, 3, 4]])

result = np.hsplit(arr, 2)

print(result)

[array([[1, 2]]), array([[3, 4]])]


In [42]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

result = np.vsplit(arr, 2)

print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


### Broadcasting

Broadcasting is a powerful feature in NumPy that allows arrays of different shapes to perform operations together without explicitly reshaping them.

In [43]:
import numpy as np
arr = np.array([1, 2, 3])
result = arr + 5

print(result)   # [6 7 8]

[6 7 8]


👉 Here, 5 is automatically applied to all elements

👉 NumPy "broadcasts" the scalar to match array size

In [44]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

print(arr1 + arr2)   # [11 22 33]

[11 22 33]


In [45]:
import numpy as np
prices = np.array([100, 200, 300])
discount = 30
final_prices = prices - (prices * discount/100)

print(final_prices)

[ 70. 140. 210.]


In [46]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[10],
                 [20]])

print(arr1 + arr2)

[[11 12 13]
 [24 25 26]]


### Vectorization
Vectorization means performing operations on entire arrays at once instead of using loops.

👉 It makes code faster, shorter, and more efficient


In [47]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = arr1 + arr2
print(result)

[5 7 9]


### Vectorization vs Broadcasting

### Vectorization
Vectorization means performing operations on entire arrays at once without using explicit loops.

It improves performance and speed

Uses optimized NumPy internal implementation (C-level)

### Broadcasting

Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array.

Makes arrays shape-compatible

Happens before vectorized operation


### Handling Missing Values
In NumPy, missing values are usually represented as:

np.nan → Not a Number (for float arrays)

#### Creating Missing Values

In [48]:
import numpy as np

arr = np.array([1, 2, np.nan, 4, np.nan])

print(arr)
# [ 1.  2. nan  4. nan]

[ 1.  2. nan  4. nan]


#### Detect Missing Values

In [51]:

print(np.isnan(arr))
# [False False True False True]

[False False  True False  True]


#### Replace Missing Values with 0


In [52]:
cleaned_arr = np.nan_to_num(arr, nan=100)
cleaned_arr

array([  1.,   2., 100.,   4., 100.])

#### Replace Inf


In [54]:
import numpy as np

arr = np.array([1, 2, np.inf, 4, -np.inf, 6])

print(np.isinf(arr))

cleaned_arr = np.nan_to_num(arr, posinf=1000, neginf=-1000)

print(cleaned_arr)

[False False  True False  True False]
[    1.     2.  1000.     4. -1000.     6.]
